#!/usr/bin/env bash 
#Install necessary tools and update Nginx configuration
apt-get update
apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/g; s/listen 80 default_server;/listen 8080;/g' /etc/nginx/nginx.conf /etc/nginx/sites-available/default

# Restart Nginx to apply changes and verify status
systemctl restart nginx
systemctl status nginx

