#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers


# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  skomaiya_frontend
        bind *:80
        mode http
        default_backend skomaiya_backend
backend skomaiya_backend
        balance roundrobin
        server 5901-web-01 52.204.120.217:80 check
        server 5901-web-02 54.234.195.24:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy/

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart

