#!/usr/bin/env bash
#Transfering a file to your server
if [ "$#" -lt 4 ]; then 
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

scp -0 StrictHostKeyChecking=no -i "$4" "$1" "$username"@"$server_ip":~/

