#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine nginx

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
service nginx restart

