#!/usr/bin/env bash
# Configuring  Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

# redirection config
replacement="server_name _;\\
    rewrite ^/redirect_me https://github.com/Skomaiya/ permanent;"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx start

