#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom HTML file for the 404 page
echo '<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n&apos;est pas une page.</p>
</body>
</html>' | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF'

# Restart Nginx
sudo service nginx restart

